# Generated by Django 4.1.7 on 2023-02-18 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorias',
        ),
        migrations.RenameField(
            model_name='categorias',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='password',
            new_name='senha',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='telefone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
