# Generated by Django 4.1.7 on 2023-02-18 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_category_categorias_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Clientes',
        ),
        migrations.RenameModel(
            old_name='Order',
            new_name='Pedidos',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Produtos',
        ),
    ]
