# Generated by Django 4.1.7 on 2023-02-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_categorias_categoria_rename_clientes_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='sobrenome',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
