# Generated by Django 4.1.7 on 2023-02-19 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_cliente_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='password',
        ),
    ]
