# Generated by Django 4.1.7 on 2023-02-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_cliente_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
