# Generated by Django 4.1.7 on 2023-02-25 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_pedido_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='Tamanho_G',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='Tamanho_M',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='Tamanho_P',
            field=models.BooleanField(default=True),
        ),
    ]
