# Generated by Django 4.1.7 on 2023-02-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_produto_tamanho_g_produto_tamanho_m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='size',
            field=models.CharField(blank=True, default='P', max_length=50),
        ),
    ]
