# Generated by Django 4.1.7 on 2023-02-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_pedido_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='address',
            field=models.CharField(default='', max_length=150),
        ),
    ]
